#!/bin/bash

set -e

if [[ $# == 0 ]]; then
    echo "Specify the tag in \`YYYY.MM\` like \`2005.09\`"
    exit 1;
fi

tag=$1

# MTG перестали ставить версионные теги (последний 5.8), поэтому
#   - используем master и не ставим теги на master-ветках сплитов
#   - ставим теги только на lord-ветках сплитов, применяя `YYYY.MM` формат

cd _MTG
git fetch -p
git fetch upstream
git checkout master
git pull upstream master
# см. коммент выше  git reset $tag --hard
git push
cd ..

./for-each-dir.split master
# см. коммент выше  ./for-splitted-repo.tag master $tag


cd _MTG/
git checkout lord
git pull
git merge master --no-edit
git push
git tag $tag-lord
git push --tags
cd ..

./for-each-dir.split lord
./for-splitted-repo.tag lord $tag-lord
