#!/bin/bash

set -e

repo=$1;
clone=$2;

function repo_not_exists() {
  local repository=$1
  [ $(curl -s -o /dev/null -w "%{http_code}" https://github.com/minetest-game-mod/$repository) == '404' ];
}

if repo_not_exists $repo; then
  gh repo create minetest-game-mod/$repo -d "[READ ONLY] Minetest mod $repo (Splitted from minetest_game)" --disable-issues --disable-wiki --public $clone
fi
