#!/bin/bash

. colors

cd _MTG;
while read dir; do
	if [ -d mods/$dir ]; then
		c.header "Processing $cyan\$dir$purple: $yellow$dir$purple"
		echo "command: $yellow$1$purple$reset"
		eval "$1";
		echo;
	fi;
done <<< $(for i in mods/*; do echo "${i:5}"; done);
cd ..;
