
name: Split into separate mods
on: workflow_dispatch
#  schedule:
#    - cron: 5 4 * * *
#  push:
#    branches:
#      - master

jobs:
  split-the-repo:
    runs-on: ubuntu-latest
    env:
      token: ${{secrets.TOKEN}}
    steps:
      - name: Clone Self
        uses: actions/checkout@v2

      - name: GH Auth
        run: echo ${{secrets.TOKEN}} | gh auth login --with-token

      - name: Clone Lord-MTG
        run: gh repo clone lord-server/minetest_game _MTG

#      - name: Update MTG From Original Upstream
#        run: |
#          cd _MTG
#          git remote add upstream https://alek13:${{secrets.TOKEN}}@github.com/minetest/minetest_game.git
#          git config pull.ff only
#          git checkout master
#          git pull upstream master
#          git push origin master
#          git checkout stable-5
#          git pull upstream stable-5
#          git push origin stable-5
#          cd ..

      - name: Create Repos If Not Exists
        run: ./for-each-dir '../create-repo-if-not-exist $dir'

      - name: Add Remotes
        run: ./for-each-dir 'git remote add mtg-mod-$dir git@github.com:minetest-game-mod/$dir.git'

      - name: Separate Directories Push
        run: |
          cd _MTG
          git checkout master
          cd ..
          ./for-each-dir 'git subtree push -P mods/$dir mtg-mod-$dir master'
