
name: Split into separate mods
on:
#  schedule:
#    - 5 4 * * *
  push:
    branches:
      - master

jobs:
  split-the-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Self
        uses: actions/checkout@v2

      - name: Clone MTG
        run: git clone https://alek13:${{secrets.TOKEN}}@github.com/lord-server/minetest_game.git
#        uses: actions/checkout@v2
#        with:
#          repository: lord-server/minetest_game
#          path: minetest_game

      - name: Test check
        run: |
          cd minetest_game
          git status
          git remote -v

#      - name: Add Remotes
#        run: |
#          git remote add ...
