
name: Split into separate mods
on:
#  schedule:
#    - 5 4 * * *
  push:
    branches:
      - master

jobs:
  split-the-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Self
        uses: actions/checkout@v2

      - name: Clone MTG
        uses: actions/checkout@v2
        with:
          repository: lord-server/minetest_game

      - name: Test check
        run: |
          cd minetest_game
          git status
