
name: Split into separate mods
on:
  schedule:
    - 5 4 * * *
  push:
    branches:
      - master

jobs:
  split-the-repo:
    runs-on: ubuntu-latest
    env:
      token: ${{secrets.TOKEN}}
    steps:
      - name: Clone Self
        uses: actions/checkout@v2

      - name: Clone Lord-MTG
        run: git clone https://alek13:${{secrets.TOKEN}}@github.com/lord-server/minetest_game.git

      - name: Update MTG From Original Upstream
        run: |
          cd minetest_game
          git remote add upstream https://alek13:${{secrets.TOKEN}}@github.com/minetest/minetest_game.git
          git config pull.ff only
          git checkout master
          git pull upstream master
          git push origin master
          git checkout stable-5
          git pull upstream stable-5
          git push origin stable-5
          cd ..

      - name: Create Repos If Not Exists
        run: |
          echo ${{secrets.TOKEN}} | gh auth login --with-token
          ./for-each '../create-repo-if-not-exist $dir'

      - name: Add Remotes
        run: ./for-each 'git remote add mtg-mod-$dir https://alek13:${{secrets.TOKEN}}@github.com/minetest-game-mod/$dir.git'

      - name: Separate Directories Push
        run: |
          cd minetest_game
          git checkout master
          cd ..
          ./for-each 'git subtree push -P mods/$dir mtg-mod-$dir master'
